version: "3.8"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
